
clc; clear;

net = googlenet; 
lgraph = layerGraph(net);

imds = imageDatastore('yuz_verileri', ...
    'IncludeSubfolders', true, ...
    'LabelSource', 'foldernames');

[imdsTrain, imdsValidation] = splitEachLabel(imds, 0.7, 'randomized');
inputSize = net.Layers(1).InputSize; 
augimdsTrain = augmentedImageDatastore(inputSize(1:2), imdsTrain, 'ColorPreprocessing', 'gray2rgb');
augimdsValidation = augmentedImageDatastore(inputSize(1:2), imdsValidation, 'ColorPreprocessing', 'gray2rgb');

numClasses = numel(categories(imdsTrain.Labels));

newConnectedLayer = fullyConnectedLayer(numClasses, ...
    'Name', 'new_fc', ...
    'WeightLearnRateFactor', 10, ...
    'BiasLearnRateFactor', 10);

newClassificationLayer = classificationLayer('Name', 'new_classoutput');

lgraph = replaceLayer(lgraph, 'loss3-classifier', newConnectedLayer);
lgraph = replaceLayer(lgraph, 'output', newClassificationLayer);

options = trainingOptions('sgdm', ...
    'ExecutionEnvironment', 'gpu', ...
    'MiniBatchSize', 10, ...
    'MaxEpochs', 40, ...
    'InitialLearnRate', 1e-4, ...
    'ValidationData', augimdsValidation, ...
    'ValidationFrequency', 3, ...
    'Verbose', false, ...
    'Plots', 'training-progress'); 

fprintf('Derin öğrenme eğitimi başlıyor...\n');
yeniNet = trainNetwork(augimdsTrain, lgraph, options);

save('DerinYoklamaModeli.mat', 'yeniNet');
disp('Model başarıyla eğitildi ve kaydedildi!');
